#!/bin/bash

# Adapted from original pipeline provided by Marta Ibañez Lligoña
# Contact: marta.ibanez@vhir.org

## Input path: Clumpify output FASTQ files
CLEAN_PATH="/home/sumeyye/Desktop/GBS1_26/results/clumpify"

## Reference genome (human, indexed for bowtie2)
REF_GENOME="/home/sumeyye/Desktop/GBS1_26/reference/human/Homo_sapiens"

## Create directories
mkdir -p "/home/sumeyye/Desktop/GBS1_26/results/logs/bowtie2"
mkdir -p "/home/sumeyye/Desktop/GBS1_26/results/mapped"
mkdir -p "/home/sumeyye/Desktop/GBS1_26/results/mapped_sorted"
mkdir -p "/home/sumeyye/Desktop/GBS1_26/results/unmapped"
mkdir -p "/home/sumeyye/Desktop/GBS1_26/results/filtered_fastqs"

## Set output paths
LOG_PATH="/home/sumeyye/Desktop/GBS1_26/results/logs/bowtie2"
MAPPED_PATH="/home/sumeyye/Desktop/GBS1_26/results/mapped"
SORTED_PATH="/home/sumeyye/Desktop/GBS1_26/results/mapped_sorted"
UNMAPPED_PATH="/home/sumeyye/Desktop/GBS1_26/results/unmapped"
UNMAPPED_FASTQ="/home/sumeyye/Desktop/GBS1_26/results/filtered_fastqs"

## loop through fastq files
for sample in $FILE_NAMES
do
    ## set input file names
    echo Mapping starting for $sample
    in1="${sample}_R1.fastq.gz"
    in2="${sample}_R2.fastq.gz"
    ## Alignment to reference with bowtie2
    bowtie2 --very-sensitive-local --mm --threads 6 --reorder --seed 4 -x $REF_GENOME -1 $in1 -2 $in2 -S "$MAPPED_PATH/$(basename $sample).sam" #> "$LOG_PATH/$(basename $sample)_alignment.log"
    ## Convert SAM file to BAM file
    samtools view -@ 2 -bS "$MAPPED_PATH/$(basename $sample).sam" > "$MAPPED_PATH/$(basename $sample).bam"
    ## | samtools view -o "$MAPPED_PATH/$(basename $sample).bam"
    echo Mapping to reference genome for $in1 and $in2 done
done

## Move to mapped folder to sort bam files
echo Moving to folder $MAPPED_PATH
MAPPED_NAMES=$(find $MAPPED_PATH -type f -name "*.bam" | rev |cut -c 5- | rev | sort -u)
echo $MAPPED_NAMES

## Loop to sort bam files and extract unmapped reads into new fastq files
for file in $MAPPED_NAMES
do
    ## SORT BAM FILE
    echo The sample being sorted is "$MAPPED_PATH/$(basename $file).bam"
    samtools sort -n "$MAPPED_PATH/$(basename $file).bam" -o "$SORTED_PATH/$(basename $file)_sorted.bam"
    ## -f pot ser o 5 o 8
    ## EXTRACT UNMAPPED READS FROM SORTED BAM FILE
    samtools view -@ 4 -b -f 12 -F 256   "$SORTED_PATH/$(basename $file)_sorted.bam" > "$UNMAPPED_PATH/$(basename $file)_UNMAP.bam"
    out1="$UNMAPPED_FASTQ/$(basename $file)_R1.fastq.gz"
    out2="$UNMAPPED_FASTQ/$(basename $file)_R2.fastq.gz"
    ## Transform to fastq files 
    samtools fastq  -@ 6  -1 $out1 -2 $out2 -n "$UNMAPPED_PATH/$(basename $file)_UNMAP.bam"
    echo BAM file with unmapped reads created with sample $file
done
