#!/bin/bash

# Adapted from original pipeline provided by Marta Ibañez Lligoña
# Contact: marta.ibanez@vhir.org

## set path to fastq files  that have had the human reads removed (bowtie2)
FILTERED_FASTQ_PATH="/home/sumeyye/Desktop/GBS1_26/results/filtered_fastqs"

## create output directory for kraken2 results
mkdir -p "/home/sumeyye/Desktop/GBS1_26/results/KRAKEN_READS"
## set path to output directory for kraken2 results
KRAKEN_PATH="/home/sumeyye/Desktop/GBS1_26/results/KRAKEN_READS"

## Set file names to be analysed, this command must be changed according to the format of the names
FILE_NAMES=$(find $FILTERED_FASTQ_PATH -type f -name "*.fastq.gz" | rev |cut -c 12- | rev | sort -u)
## print names to check
echo $FILE_NAMES

## Set path KRAKEN2 DB, last update 2025, this needs to change according to the location of the DB on your system
KRAKEN2_DB="/home/sumeyye/metagenomics/k2_pluspf_20250714"

## loop through each sample and run kraken2
for sample in $FILE_NAMES
do
    in1="${sample}R1.fastq.gz"
    in2="${sample}R2.fastq.gz"
    ## This is the name for the kraken.txt output file 1 (hard to read)
    out="$KRAKEN_PATH/$(basename $sample)_kraken.txt"
    ## this is the name for the files that will contain the classified reads
    seqsC="$KRAKEN_PATH/$(basename $sample)_classified#.fastq.gz"
    ## this is the name for the files that will contain the unclassified reads
    seqsU="$KRAKEN_PATH/$(basename $sample)_unclassified#.fastq.gz"
    ## this is the name for the kraken report file (easier to read)
    report="$KRAKEN_PATH/$(basename $sample)_kreport.txt"
    echo Running KRAKEN with $in1 and $in2
    kraken2 --db $KRAKEN2_DB --threads 6 --paired $in1 $in2  --report $report --output $out ##--unclassified-out $seqsU ##--classified-out $seqsC  ##--confidence 0.2
    echo KRAKEN2 COMPLETED!
done
